[[server]]
name = "garados"
tags = ["gitified, webserver"]
[server.config]
enabled = true

##

[[server]]
name = "pikachu"
tags = ["gitified, webserver"]
[server.config]
enabled = true

##

[[server]]
name = "snivy"
tags = ["gitified, proxy"]
[server.config]
enabled = true

##

[[stack]]
name = "papaWebsite"
tags = ["gitified"]
[stack.config]
auto_update = true
git_provider = "192.168.0.14:3500"
git_https = false
repo = "Escape9002/PapaWebsite"
webhook_enabled = false
file_paths = ["docker-compose.yml"]
pre_deploy.command = """
  # Add multiple commands on new lines. Supports comments and escaped newlines.
git submodule update --init --recursive
"""
pre_deploy.shell_mode = false

##

[[stack]]
name = "swt25w33"
tags = ["gitified"]
[stack.config]
auto_pull = false
run_build = true
linked_repo = "swt25w33"
webhook_enabled = false
file_paths = ["docker-compose.yml"]
pre_deploy.command = """
mkdir -p /srv/data/swt25w33
mkdir -p /srv/data/swt25w33/db
mkdir -p /srv/data/swt25w33/uploads
"""
pre_deploy.shell_mode = true
environment = """
  # VARIABLE = value
MOUNT_PATH=/srv/data/swt25w33
"""

##

[[deployment]]
name = "swt25w33"
tags = ["gitified"]
[deployment.config]
image.type = "Build"
image.params.build = "swt25w33"
redeploy_on_build = true

##

[[build]]
name = "swt25w33"
tags = ["gitified"]
[build.config]
builder = "Local"
linked_repo = "localswt"
webhook_enabled = false
image_registry = [
  { domain = "gitea.itwoc.de:4430", account = "escape9002" }
]

##

[[repo]]
name = "swt25w33"
tags = ["gitified"]
[repo.config]
git_account = "escape9002"
repo = "Escape9002/swt25w33"
webhook_enabled = false
environment = """
MOUNT_PATH=/home/escape9002/docker_setup/app-data/swt25w33
"""

## 
[[repo]]
name = "papaWebsite"
tags = ["gitified"]
[repo.config]
git_provider = "192.168.0.14:3500"
git_https = false
repo = "Escape9002/PapaWebsite"
webhook_enabled = false
file_paths = ["docker-compose.yml"]
pre_deploy.command = """
  # Add multiple commands on new lines. Supports comments and escaped newlines.
git submodule update --init --recursive
"""
pre_deploy.shell_mode = false
